project:
  type: website
  pre-render: download_resources.R
  resources:
    - vannmiljo_pilot.sqlite
    - libs/sqljs/
  render: 
    - "*.qmd"
    - "!CHANGELOG.md" 

website:
  title: "Vannmiljø Pilot"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/seafood-hazards/vannmiljo-pilot
        aria-label: GitHub
    left:
      - text: "Home"
        href: index.qmd
      - text: "DB Design"
        menu:
          - text: "DB Schema (Full)"
            href: db-schema.qmd
          - text: "Data Preparation"
            href: data-preparation.qmd
          - text: "Sediment Fractions"
            href: sediment-fractions.qmd
          - text: "Database Downloads"
            href: database-downloads.qmd
      - text: "Geospatial Analysis"
        menu:
          - text: "Distance to Coast"
            href: distance-to-coast.qmd
          - text: "Location Names"
            href: location-names.qmd
          - text: "Interactive Map"
            href: distance-interactive-map.qmd
      - text: "EFSA Submission"
        menu:
          - text: "EFSA Format v1"
            href: efsa-format.qmd
          - text: "EFSA Submission v1"
            href: efsa-submission.qmd
          - text: "EFSA Format v2"
            href: efsa-format-v2.qmd
          - text: "EFSA Submission v2"
            href: efsa-submission-v2.qmd
      - text: "Tools"
        menu:
          - text: "Pilot DB Viewer"
            href: pilot-db-viewer.qmd
          - text: "Trace Element Map"
            href: sediment-map.qmd

format:
  html:
    include-in-header: header.html
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    df-print: kable

execute:
  echo: false
  warning: false
  message: false
